name: camilo_verde
description: "App oficial del proyecto PRAE del Camilo Torres"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  path_provider: ^2.1.2  
  gal: ^2.1.4
  video_player: ^2.10.1
  url_launcher: ^6.3.2
  http: ^1.6.0
  flame: ^1.22.0
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#72FD6B"
  adaptive_icon_foreground: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/camilorunner/
    - assets/camilorunner/Animations/
    - assets/camilorunner/Sprites/
    - assets/camilorunner/Sprites/Game Objects/
    - assets/camilorunner/Sprites/UI Elements/
